version: '{build}'
skip_tags: true
environment:
  TERM: dumb
install:
  - SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - echo %PATH%
  - java -version
  - mvnw.cmd --version
  - mvnw.cmd dependency:go-offline
build_script:
  - mvnw.cmd -Dmaven.javadoc.skip=true -B clean compile
test_script:
  - mvnw.cmd -Dmaven.javadoc.skip=true verify
